name: departamentos_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.3.4
  flutter:
    sdk: flutter
  http: ^0.13.3
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  ios: true
  android: true
  image_path: 'assets/icon/icon.png'


flutter:
  uses-material-design: true



